import type { Metadata } from 'next'
import './globals.css'
import { Navigation } from '@/components/nav'
import { UserProvider } from '@/components/context/user-context'
import { createSSRClient } from '@/lib/supabase/ssr-client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const supabaseSSR = await createSSRClient()

  const {
    data: { user },
    error: userError,
  } = await supabaseSSR.auth.getUser()
  // const { data: profile, error: profileError } = await supabaseSSR
  //   .from('profiles')
  //   .select('*')
  //   .eq('auth_id', user?.id ?? '')
  //   .maybeSingle()

  let userProfile =
    user ? { user, profile: undefined } : undefined

  return (
    <html lang='en'>
      <body className={`font-sans antialiased`}>
        <div className='wrapper'>
          <UserProvider init={userProfile}>
            <Navigation />
            {children}
          </UserProvider>
        </div>
      </body>
    </html>
  )
}
