import type { Metadata } from 'next'
import './globals.css'
import { Navigation } from '@/components/nav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`font-sans antialiased`}>
        <div className='wrapper'>
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  )
}
